// apps/web-v1/src/components/MakerSettings.vue
<template>
	<div style="height: 16px" />
	<baud-rate />
	<div style="height: 16px" />
	<serial-first-column />
</template>

<script>
import SerialFirstColumn from "@/components/SerialFirstColumn.vue"

import BaudRate from "./BaudRate.vue"

export default {
	name: "MakerSettings",
	components: {
		SerialFirstColumn,
		BaudRate
	}
}
</script>

<style scoped></style>

// apps/sense-web-v2/src/views/settings/MakerSettings.tsx
import { NumberField } from "@scientisst/react-ui/components/inputs"

const makerSettings = () => {
	
    return (
        <>
            <NumberField
                label="Baud Rate"
                name="baudRate"
                id="baudRate"
                min={0}
                max={16000}
                center
                className="w-full max-w-[29.25rem]"
            />
        </>
    )
}

export default makerSettings
